### ISSUE TITLE
reia -v dumps

### ISSUE THREAD

**Issue by djberg96** [tarcieri/reia#11]
Hi,

Just trying reia out. I ran rake + rake install - no problems.

Ubuntu Linux
reia - latest from git repo (27-Oct-2010)

> erl -v
> Erlang R13B03 (erts-5.7.4) [source] [smp:2:2] [rq:2] [async-threads:0] [hipe] [kernel-poll:false]

But I hit this. Is this normal?

> reia -v
> {"init terminating in do_boot",{undef,[{reia_internal,execute_file,[]},{init,start_it,1},{init,start_em,1}]}}

**Comment by djberg96** [comment]
Looks like it's dead.

**Comment by graeme-defty** [comment]
Sadly Reia was abandoned some time ago.

The good news is that it was abandoned because another project existed with
many of the same goals and was more advanced at the time.

Take a look at Xlixir (http://elixir-lang.org/). You will find an active
project there which will have a lot of what you want.

graeme
